/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrainsRouteImport } from './routes/_authenticated/brains'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedWorkflowsWorkflowIdRouteImport } from './routes/_authenticated/workflows.$workflowId'
import { Route as AuthenticatedEmployeesEmployeeIdRouteImport } from './routes/_authenticated/employees.$employeeId'
import { Route as AuthenticatedBrainsBrainIdRouteImport } from './routes/_authenticated/brains.$brainId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrainsRoute = AuthenticatedBrainsRouteImport.update({
  id: '/brains',
  path: '/brains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsWorkflowIdRoute =
  AuthenticatedWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => AuthenticatedWorkflowsRoute,
  } as any)
const AuthenticatedEmployeesEmployeeIdRoute =
  AuthenticatedEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)
const AuthenticatedBrainsBrainIdRoute =
  AuthenticatedBrainsBrainIdRouteImport.update({
    id: '/$brainId',
    path: '/$brainId',
    getParentRoute: () => AuthenticatedBrainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/brains': typeof AuthenticatedBrainsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/brains/$brainId': typeof AuthenticatedBrainsBrainIdRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/brains': typeof AuthenticatedBrainsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/brains/$brainId': typeof AuthenticatedBrainsBrainIdRoute
  '/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/brains': typeof AuthenticatedBrainsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRouteWithChildren
  '/_authenticated/brains/$brainId': typeof AuthenticatedBrainsBrainIdRoute
  '/_authenticated/employees/$employeeId': typeof AuthenticatedEmployeesEmployeeIdRoute
  '/_authenticated/workflows/$workflowId': typeof AuthenticatedWorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/attendance'
    | '/brains'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/knowledge'
    | '/settings'
    | '/skills'
    | '/templates'
    | '/tools'
    | '/workflows'
    | '/brains/$brainId'
    | '/employees/$employeeId'
    | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/attendance'
    | '/brains'
    | '/dashboard'
    | '/documents'
    | '/employees'
    | '/knowledge'
    | '/settings'
    | '/skills'
    | '/templates'
    | '/tools'
    | '/workflows'
    | '/brains/$brainId'
    | '/employees/$employeeId'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/attendance'
    | '/_authenticated/brains'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/employees'
    | '/_authenticated/knowledge'
    | '/_authenticated/settings'
    | '/_authenticated/skills'
    | '/_authenticated/templates'
    | '/_authenticated/tools'
    | '/_authenticated/workflows'
    | '/_authenticated/brains/$brainId'
    | '/_authenticated/employees/$employeeId'
    | '/_authenticated/workflows/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brains': {
      id: '/_authenticated/brains'
      path: '/brains'
      fullPath: '/brains'
      preLoaderRoute: typeof AuthenticatedBrainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/$workflowId': {
      id: '/_authenticated/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedWorkflowsRoute
    }
    '/_authenticated/employees/$employeeId': {
      id: '/_authenticated/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AuthenticatedEmployeesEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
    '/_authenticated/brains/$brainId': {
      id: '/_authenticated/brains/$brainId'
      path: '/$brainId'
      fullPath: '/brains/$brainId'
      preLoaderRoute: typeof AuthenticatedBrainsBrainIdRouteImport
      parentRoute: typeof AuthenticatedBrainsRoute
    }
  }
}

interface AuthenticatedBrainsRouteChildren {
  AuthenticatedBrainsBrainIdRoute: typeof AuthenticatedBrainsBrainIdRoute
}

const AuthenticatedBrainsRouteChildren: AuthenticatedBrainsRouteChildren = {
  AuthenticatedBrainsBrainIdRoute: AuthenticatedBrainsBrainIdRoute,
}

const AuthenticatedBrainsRouteWithChildren =
  AuthenticatedBrainsRoute._addFileChildren(AuthenticatedBrainsRouteChildren)

interface AuthenticatedEmployeesRouteChildren {
  AuthenticatedEmployeesEmployeeIdRoute: typeof AuthenticatedEmployeesEmployeeIdRoute
}

const AuthenticatedEmployeesRouteChildren: AuthenticatedEmployeesRouteChildren =
  {
    AuthenticatedEmployeesEmployeeIdRoute:
      AuthenticatedEmployeesEmployeeIdRoute,
  }

const AuthenticatedEmployeesRouteWithChildren =
  AuthenticatedEmployeesRoute._addFileChildren(
    AuthenticatedEmployeesRouteChildren,
  )

interface AuthenticatedWorkflowsRouteChildren {
  AuthenticatedWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkflowsWorkflowIdRoute
}

const AuthenticatedWorkflowsRouteChildren: AuthenticatedWorkflowsRouteChildren =
  {
    AuthenticatedWorkflowsWorkflowIdRoute:
      AuthenticatedWorkflowsWorkflowIdRoute,
  }

const AuthenticatedWorkflowsRouteWithChildren =
  AuthenticatedWorkflowsRoute._addFileChildren(
    AuthenticatedWorkflowsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBrainsRoute: typeof AuthenticatedBrainsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRouteWithChildren
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBrainsRoute: AuthenticatedBrainsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRouteWithChildren,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
